Map<String, String> coreAr = {
  'English': 'الإنجليزية',
  'Biology': 'الأحياء',
  'Mathematics': 'الرياضيات',
  'Arabic': 'اللغة العربية',
  'Physics': 'الفيزياء',
  'Chemistry': 'الكيمياء',
  'Hello,': 'مرحبًا،',
  'GoodMorning': 'صباح الخير',
  'ExploreSubjects': 'استكشاف الموضوعات',
  'Unit-': 'الوحدة-',
  'Book': 'كتاب',
  'Quiz': 'اختبار',
  'Note': 'ملحوظة',
  'Are you Ready?': 'هل أنت جاهز؟',
  'Questions': 'أسئلة',
  'Okay': 'تمام',
  'Notes': 'ملاحظات',
  'Title': 'عنوان',
  'Note Something down': 'لاحظ شيئا إلى أسفل',
  'Algebra': 'الجبر',
  'Dynamics': 'الديناميكيات',
  'Statics': 'علم الإحصاء',
  'Calculus': 'التفاضل',
  'Integration': 'التكامل',
  'Contact': 'اتصال',
  'FirstName': 'الاسم الأول',
  'SecondName': 'الاسم الثاني',
  'FullName': 'الاسم الكامل',
  'MessageName': 'اسم الرسالة',
  'Send': 'يرسل',
  'community': 'تواصل اجتماعي',
  'typeMessage': 'اكتب رسالة',
  'Like': 'اعجبنى',
  'Reply': 'الرد',
  'Delete': 'حذف',
  'WhatsInYourMind': 'في ماذا تفكر؟',
  'ConfirmDeletePost': 'هل أنت متأكد من حذف المنشور',
  'Type Reply': 'اكتب الرد',
  'ConfirmDeleteComment': 'هل أنت متأكد من حذف التعليق؟',
  'Type Comment': 'اكتب التعليق',
};
