Map<String, String> coreEn = {
  'English': 'English',
  'Biology': 'Biology',
  'Mathematics': 'Mathematics',
  'Arabic': 'Arabic',
  'Physics': 'Physics',
  'Chemistry': 'Chemistry',
  'Hello,': 'Hello,',
  'GoodMorning': 'Good Morning',
  'ExploreSubjects': 'Explore Subjects',
  'Unit-': 'Unit-',
  'Book': 'Book',
  'Quiz': 'Quiz',
  'Note': 'Note',
  'Are you Ready?': 'Are you Ready?',
  'Questions': 'Questions',
  'Okay': 'Okay',
  'Notes': 'Notes',
  'Title': 'Title',
  'Note Something down': 'Note Something down',
  'Algebra': 'Algebra',
  'Dynamics': 'Dynamics',
  'Statics': 'Statics',
  'Calculus': 'Calculus',
  'Integration': 'Integration',
  'Contact': 'Contact',
  'FirstName': 'First Name',
  'SecondName': 'Second Name',
  'FullName': 'Full Name',
  'MessageName': 'Message Name',
  'Send': 'Send',
  'community': 'Community',
  'typeMessage': 'Type Message',
  'Like': 'Like',
  'Reply': 'Reply',
  'Delete': 'Delete',
  'WhatsInYourMind': 'What\'s on your mind?',
  'ConfirmDeletePost': 'Are you sure to delete Post?',
  'Type Reply': 'Type Reply',
  'ConfirmDeleteComment': 'Are you sure to delete comment?',
  'Type Comment': 'Type Comment',
};
